### ISSUE TITLE
The ciphertext is too long to be transmitted and must rely on file transfer

### ISSUE THREAD

**Issue by freelyyu** [OpenSMP/SMP#1]
密文太长不能传输过去,必须依赖文件传输
The ciphertext is too long to be transmitted and must rely on file transfer

**Comment by fionser** [comment]
how about just replace the network IO with a file stream

**Comment by fionser** [comment]
Most of the HElib's object is overloading the "operator<<" and "operator>>" operators.

**Comment by freelyyu** [comment]
boost是用来干啥的  这个testnetio可以实现加密和解密吗

**Comment by fionser** [comment]
1. just baidu or google what is Boost. I just used one of the features of it, i.e., network interface.
2. TestNetIO just show how to transfer the ciphertext via network.
